// Code generated by go generate; DO NOT EDIT.
// +build linux_bpf

package runtime

var RuntimeSecurity = NewRuntimeAsset("runtime-security.c", "f1edef57abcdae91f6e5baaeb8ebe5b8f5edb43a6851df58966d24e7abd04964")
