// Code generated by go generate; DO NOT EDIT.
// +build linux_bpf

package runtime

var RuntimeSecurity = NewRuntimeAsset("runtime-security.c", "68f6ab16f9bca2bede95d4cbaa54116b73910f32555c9ff30c60acb64f65105a")
